### ISSUE TITLE
Any thoughts on Octane Support

### ISSUE THREAD

**Issue by jrock2004** [josemarluedke/ember-vim-snippets#10]
Any thoughts on converting to octane syntax?

**Comment by jrock2004** [comment]
Maybe prefix or suffix of `oc` or something like that? `ocroute`

**Comment by josemarluedke** [comment]
I would definitely like to see it supporting Octane by default. If you have cycles, please send PRs.

**Comment by jrock2004** [comment]
Sure, I have some time. Any ideas? Would you want octane to replace and make a prefix for old style? Just need some pointers on where to go so I do not go wrong direction

**Comment by josemarluedke** [comment]
I think it should replace all older content. Ember Octane is now the default and so I think it should be the default here as well.

**Comment by jrock2004** [comment]
Any backwards compatibility?

**Comment by josemarluedke** [comment]
Nope, I will create a tag, if folks need the old version they could use the tag.

**Comment by jrock2004** [comment]
Ok, I am working through this now. Might have a PR up later tonight
