### ISSUE TITLE
How to use Convert file

### ISSUE THREAD

**Issue by jrock2004** [josemarluedke/ember-vim-snippets#2]
Is that file used to convert from a filepath? I am asking because there has been recent updates to the atom snippets and would like to see this repo updated. Just wondering if I need to do by hand or is there a quick way?

**Comment by josemarluedke** [comment]
Unfortunately, it is not automatic, we need to convert manually.

To convert, use this project http://github.com/binaryoung/convert-atom-snippets-to-vscode to a folder `converted` then run the script in this project.

**Comment by jrock2004** [comment]
@josemarluedke so I did that and it seems to only work on the files that start with the word import

**Comment by jrock2004** [comment]
Here is the new ember file what it looks like in VSCode https://github.com/jrock2004/vscode-ember-snippets/blob/master/snippets/ember.json
